[package]
name = "typeset"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii85 = "0.2.1"
glam = "0.27.0"
itertools = "0.12.1"
thiserror = "1.0.58"
ttf-parser = "0.20.0"

[build-dependencies]
ureq = "2.9.6"

[dev-dependencies]
ring = "0.17.13"
