name: macOS QuickLook

on: [push]

jobs:
  quicklook:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create directory
        run: mkdir -p output/
      - name: Generate thumbnail
        run: qlmanage -t -s 4000 -o output/ examples/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QuickLook Thumbnails
          path: output/
